"""Detect the connected SIXTH board and write .board.conf automatically.

Uses `arduino-cli board list` to find the USB port and FQBN, then opens the
serial monitor briefly to watch for the sketch's "Listening on <ip>:4040"
line so we can fill in WIFI_TARGET too.

Usage:
    python3 firmware/bridge/setup_board.py
    python3 firmware/bridge/setup_board.py --skip-wifi
    python3 firmware/bridge/setup_board.py --wifi-timeout 30 --default-transport serial

If the board isn't flashed yet (or WiFi creds aren't filled in), WIFI_TARGET
will be left empty; re-run after flashing to populate it.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import time
from pathlib import Path
from typing import Optional


_WIFI_LINE_RE = re.compile(r"Listening on\s+(\S+):(\d+)")
_USB_PREFIXES = (
    "/dev/tty.usbmodem",
    "/dev/tty.usbserial",
    "/dev/cu.usbmodem",
    "/dev/cu.usbserial",
)


def detect_arduino_board() -> tuple[Optional[str], Optional[str]]:
    """Return (port, fqbn) for the first USB-connected board, or (None, None)."""
    try:
        result = subprocess.run(
            ["arduino-cli", "board", "list", "--format", "json"],
            capture_output=True,
            text=True,
            timeout=15,
            check=True,
        )
    except FileNotFoundError:
        print(
            "Error: arduino-cli not found on PATH. Install with 'brew install arduino-cli'.",
            file=sys.stderr,
        )
        sys.exit(1)
    except subprocess.CalledProcessError as e:
        print(f"Error: arduino-cli failed:\n{e.stderr}", file=sys.stderr)
        sys.exit(1)

    data = json.loads(result.stdout)
    ports = data.get("detected_ports", []) if isinstance(data, dict) else []

    for p in ports:
        address = p.get("port", {}).get("address", "")
        if not address.startswith(_USB_PREFIXES):
            continue
        boards = p.get("matching_boards") or []
        fqbn = boards[0].get("fqbn") if boards else None
        return address, fqbn
    return None, None


def detect_wifi_target(port: str, timeout_s: float) -> Optional[str]:
    """Read serial output and return 'ip:port' from the sketch's banner, or None."""
    try:
        import serial  # pyserial
    except ImportError:
        print(
            "Error: pyserial not installed. Run 'pip install -r requirements.txt'.",
            file=sys.stderr,
        )
        sys.exit(1)

    try:
        ser = serial.Serial(port, 115200, timeout=0.5)
    except serial.SerialException as e:
        print(
            f"Warn: can't open {port} ({e}). Close any other program using it "
            "(Arduino IDE Serial Monitor, screen, etc.) and retry.",
            file=sys.stderr,
        )
        return None

    buf = b""
    deadline = time.monotonic() + timeout_s
    try:
        while time.monotonic() < deadline:
            chunk = ser.read(256)
            if chunk:
                buf += chunk
                text = buf.decode("utf-8", errors="replace")
                for line in text.splitlines():
                    m = _WIFI_LINE_RE.search(line)
                    if m:
                        return f"{m.group(1)}:{m.group(2)}"
            else:
                time.sleep(0.1)
    finally:
        ser.close()
    return None


def write_conf(path: Path, values: dict[str, str]) -> None:
    lines = [
        "# Auto-generated by firmware/bridge/setup_board.py",
        "# Edit by hand to override; re-run the script to regenerate.",
        "",
    ]
    for k, v in values.items():
        lines.append(f"{k}={v}")
    path.write_text("\n".join(lines) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Auto-detect the SIXTH board and write .board.conf"
    )
    parser.add_argument(
        "--wifi-timeout",
        type=float,
        default=15.0,
        help="Seconds to wait for the sketch to announce its IP (default 15)",
    )
    parser.add_argument(
        "--skip-wifi",
        action="store_true",
        help="Don't try to detect WIFI_TARGET (useful before flashing)",
    )
    parser.add_argument(
        "--default-transport",
        choices=["serial", "wifi"],
        default="wifi",
        help="Value for DEFAULT_TRANSPORT (default wifi)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Path to .board.conf (default: repo root)",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[2]
    output = args.output or (repo_root / ".board.conf")

    print("Detecting board via arduino-cli...")
    port, fqbn = detect_arduino_board()
    if not port:
        print(
            "Error: no USB board detected. Plug in the board and retry.",
            file=sys.stderr,
        )
        return 1
    print(f"  port: {port}")
    print(f"  fqbn: {fqbn or '(unknown — defaulting to esp32:esp32:featheresp32)'}")

    wifi_target: Optional[str] = None
    if not args.skip_wifi:
        print(f"Reading serial for up to {args.wifi_timeout:.0f}s to find WIFI_TARGET...")
        wifi_target = detect_wifi_target(port, args.wifi_timeout)
        if wifi_target:
            print(f"  wifi: {wifi_target}")
        else:
            print("  wifi: not found (sketch may not be flashed or WiFi creds not set)")

    overwrite_note = " (overwriting existing)" if output.exists() else ""
    values = {
        "SERIAL_PORT": port,
        "WIFI_TARGET": wifi_target or "",
        "DEFAULT_TRANSPORT": args.default_transport,
        "FQBN": fqbn or "esp32:esp32:featheresp32",
    }
    write_conf(output, values)
    print(f"\nWrote {output}{overwrite_note}")

    if not fqbn:
        print(
            "Note: FQBN defaulted — verify with 'arduino-cli board listall esp32 | grep -i feather' if wrong."
        )
    if not wifi_target and not args.skip_wifi:
        print("Note: WIFI_TARGET left empty — flash the sketch, then re-run to populate it.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
